name: notevault
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  provider: ^6.0.3
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.1.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/angry.png
    - assets/lucky.png
    - assets/blessed.png
    - assets/loved.png
    - assets/sick.png
    - assets/laughed.png